#devlopment repository
name: trigger test in another reposirotys
on: workflow_dispatch
jobs:
  build:
    # Main workflow job that builds, tests, etc.

  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['devlopment-demo/devlopmentaction', 'devlopment-demo/devrepC']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONTOKEN1 }}
          repository: ${{ matrix.repo }}
          event-type: my-event
