#devlopment repository
name: trigger test 
on: workflow_dispatch
jobs:

  dispatch:
    strategy:
      matrix:
        repo: ['devlopment-demo/devlopmentaction', 'devlopment-demo/devrepC']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONTOKEN1 }}
          repository: ${{ matrix.repo }}
          event-type: my-event
          
    strategy1:
      fail-fast: true

  notify:
    needs: build
    if: always()
    uses: actions/slack@v3
    with:
      status: failure
      text: "Build failed for commit ${{ github.sha }} on branch ${{ github.ref }} due to a failure in the workflow for Repo ${{ matrix.repo }}."
    if: ${{ job.status == 'failure' }}




