#devlopment repository
name: trigger test 
on: workflow_dispatch
jobs:

  dispatch:
    strategy:
      matrix:
        repo: ['devlopment-demo/devlopmentaction', 'devlopment-demo/devrepC']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONTOKEN1 }}
          repository: ${{ matrix.repo }}
          event-type: my-event
      - name: Check status of other workflows
        run: |
          for repo in ${{ matrix.repo }}; do
          status=$(curl \
          -s \
          -H "Authorization: Bearer ${{ secrets.ACTIONTOKEN1 }}" \
           https://api.github.com/repos/:owner/$repo/actions/workflows/workflow.yml/runs \
          | jq -r '.workflow_runs[0].conclusion')
          if [ "$status" != "success" ]; then
          # Send error notification to repo A
          fi
          done
      
